import { gridSize, scanRuns } from './pixels.ts'

/**
 * The cover: a manager on the touchline at night, looking out over a floodlit
 * pitch. 161 x 91, one flat grid, one character per pixel.
 *
 * **Odd in both axes**, like `stadium-plan.ts` and for the same reason — the view
 * is symmetric about the goal, so that axis has to be a real pixel rather than a
 * seam. The pitch markings are mirrored about column 80 and there is a test for
 * it, because a pitch drawn one column off-centre is invisible in source.
 *
 * **One grid, not modules.** The stadium is moduled so a ghosted tier never
 * paints over a built one; a cover has no tiers and no state, so the disjointness
 * invariant would be ceremony. And splitting it into bands would hide the thing
 * that most needed tuning: the seams *between* the bands. Full bleed, so it abuts
 * sky-to-roof-to-crowd-to-pitch-to-foreground with nothing between, and a hard
 * dark divider at every one of those joins is what stops two bands reading as a
 * single slab of concrete — the failure `stadium-plan.ts` had to be redrawn for.
 *
 * **Club-agnostic, and that is structural rather than stylistic.** `stadium.css`
 * takes its seats from `var(--badge-a)` through `data-colours`, but this renders
 * on the landing page, *before a club exists* — that is the whole point of a
 * landing page — so `badgeFor` has nothing to give it. Its palette is its own,
 * and a test asserts `cover.css` never reaches for a badge token.
 *
 * The geometry was laid down by a throwaway generator and the output pasted here
 * as literal rows, which is exactly what `stadium-plan.ts` did with its
 * concentric maths: a vanishing point and an ellipse are not things to place by
 * eye at this size. The generator is gone. Everything after it — the seams, the
 * lamp banks, the rim light, the lettering — was tuned by hand here.
 */

/** Back to front, which is the order the groups are emitted in. */
export const COVER_INK_KEYS = [
  'sky',
  'haze',
  'glow',
  'lamp',
  'mast',
  'roof',
  'stand',
  'crowd',
  'shade',
  'seam',
  'turf',
  'dusk',
  'stripe',
  'line',
  'figure',
  'rim',
  'title',
] as const

export type CoverInk = (typeof COVER_INK_KEYS)[number]

/**
 * One character per ink. Single lowercase words on the key side, because the test
 * asserts a matching `--cover-<ink>` custom property exists and a camelCase key
 * would need a translation table to get there.
 */
export const COVER_INK_BY_CHAR: Readonly<Record<string, CoverInk>> = {
  y: 'sky',
  z: 'haze',
  o: 'glow',
  l: 'lamp',
  m: 'mast',
  r: 'roof',
  n: 'stand',
  c: 'crowd',
  d: 'shade',
  k: 'seam',
  g: 'turf',
  u: 'dusk',
  s: 'stripe',
  w: 'line',
  f: 'figure',
  i: 'rim',
  t: 'title',
}

/**
 * The centre column, and the row band the pitch occupies.
 *
 * Exported so the mirror test can scope itself to the markings: the crowd and the
 * figure are deliberately *not* symmetric, and a whole-grid mirror assertion would
 * either fail or force the drawing to look mechanical.
 */
export const COVER_CENTRE = 80
export const COVER_PITCH_ROWS = { top: 35, bottom: 70 } as const

/** The drawing. One character per pixel; there are no holes. */
export const COVER_GRID: readonly string[] = [
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyyzzzmmmmmmmmmmmmmmmmmmmmmzzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzmmmmmmmmmmmmmmmmmmmmmzzzyyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyyzzzzoomoomoomoomoomoomoomzzzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzoomoomoomoomoomoomoomzzzzyyyyyyyyyyyyyy',
  'yyyyyyyyyyyyyzzzzzllmllmllmllmllmllmllmzzzzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzllmllmllmllmllmllmllmzzzzzyyyyyyyyyyyyy',
  'yyyyyyyyzzzzzzzzzzllmllmllmllmllmllmllmzzzzzzyyyzzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzllmllmllmllmllmllmllmozzzzyyyyyyyyyyyyy',
  'yyyyzzzzzzzzzzzzzzoomoomoomoomoomoomoomoooooozzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzoomoomoomoomoomoomoomoooozzzyyyyyyyyyyy',
  'zzzzyyyyzzoozzzooollmllmllmllmllmllmllmoooooozzzooyyzzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzyzzzzzllmllmllmllmllmllmllmoooozzzzzyyyyyyyyy',
  'zzzzzzzzzoooooozoollmllmllmllmllmllmllmooooooooooooozzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzooozzllmllmllmllmllmllmllmoooooozzzzozzzzzzy',
  'yyozzzoooooooooooommmmmmmmmmmmmmmmmmmmmooooooooooozoooyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyoozzzoommmmmmmmmmmmmmmmmmmmmoooooooooozzzoyyyy',
  'zzzooooooooooooooommmmmmmmmmmmmmmmmmmmmooooooooooooozzoozzzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzoozzzooooommmmmmmmmmmmmmmmmmmmmooooooooooooozzzzy',
  'zzooooooooooooooooooooooooomomoooooooooooooooooooooooooooyyyzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzyyyzzzzooozoooooooooooooooomomooooooooooooooooooooooozzoo',
  'ooooooooooooooooooooooooooommmooooooooooooooooooooooooooooozzzzzyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzyyyyzzzzzzzzooooooooooooooooooooooommmooooooooooooooooooooooooooo',
  'ooooooooooooooooooooooooooomomoooooooooooooooooooooooooooooozzzzzzzyyyyyyyyyyyyyyyyyyyyyyyyyzzzzyyyzzzooozzzzoooooooooooooooooooooomomooooooooooooooooooooooooooo',
  'ooooooooooooooooooooooooooomomoooooooooooooooooooooooooooooooooyzzzzzyyyyyyyyyyyyyyyyyyyyyyyzzzzzoozzzooooooooooooooooooooooooooooomomooooooooooooooooooooooooooo',
  'ooooooooooooooooooooooooooommmooooooooooooooooooooooooooooooozzzzzyyzyyyyyyyyyyyyzzzyyyyzzzzzzzzzzzzzoooooooooooooooooooooooooooooommmooooooooooooooooooooooooooo',
  'oooooooooooooooooooooooooomoommoooooooooooooooooooooooooooooooozzzozzzzyyyyyyyyyzzzzzzzzyyzzzzzzzooooooooooooooooooooooooooooooooomoommoooooooooooooooooooooooooo',
  'oooooooooooooooooooooooooomooomoooooooooooooooooooooooooooooooooozooozzzyyyyzzzzyzzzzzzzzzoooooooooooooooooooooooooooooooooooooooomooomoooooooooooooooooooooooooo',
  'oooooooooooooooooooooooooommmmmoooooooooooooooooooooooooooooooooooozzoooyyyyzzzzzzzzzzzzzzzooooooooooooooooooooooooooooooooooooooommmmmoooooooooooooooooooooooooo',
  'oooooooooooooooooooooooooommoomooooooooooooooooooooooooooooooooooooooooooooooooooooozzzzzooooooooooooooooooooooooooooooooooooooooommoomoooooooooooooooooooooooooo',
  'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  'rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'cccccccccccccckkcccccccnnnnnnnncccccccccccccccckkccccccccccccnnnnnncccccccccccccccccccccccccccccccccccccccccccccckkccccdddcccccccccccccccccccccnnnkknnnccccnnnnnn',
  'cccccccccccccckkcccccccnnnnnnnncccccccccccccccckkccccccccccccnnnnnncccccccccccccccccccccccccccccccccccccccccccccckkccccdddcccccccccccccccccccccnnnkknnnccccnnnnnn',
  'cccccddddddccckkdddddddccccddddddddcccccccccccckkccdddcccdddddddcccdddcccccccccccccccccccccccccccccccccccdddddddckkccdddddcccddddccccccccccccccccckkccccccccccccc',
  'cccccddddddccckkdddddddccccddddddddcccccccccccckkccdddcccdddddddcccdddcccccccccccccccccccccccccccccccccccdddddddckkccdddddcccddddccccccccccccccccckkccccccccccccc',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'ccccnnnnnncccckkccccccccccccccccccccccccdddddcckkcnnncccccccccccccccccccccccccccccccccnnnnccccccccccccccccccccccckkccccccccccccccccccccccccccccccckkccnnncccccccn',
  'dddddddcccccnnkkccccdddddddcccccccccccccccccccckkcccccccnnnnnnccccccnnnnccccccccccccccnnnnnnncccnnnnnnccccccdddddkkcccnnnncccccccccccccccccccccccckkccccccccccccc',
  'dddddddcccccddkkccccdddddddcccccccccccccccccccckkcccccccddddddccccccddddccccccccccccccdddddddcccddddddccccccdddddkkcccddddcccccccccccccccccccccccckkccccccccccccc',
  'ccccddddcccccckkccccccccccccdddddcccddddddccccckkdddddccccccccccccccccccdddddddcccccdddcccccccdddcccccccccccccccckkccccccccccccccccccccccccccccccckkccccccccdddcc',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwwwwwwwwwwwwwwwwwwwwwkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'ccccccccnnnncckkdddddcccccnnncccnnncccccnnnnccckkcccccccccccccccnnnnnnwwkkkkkkkkkkkkkkkkkwwnncccccccnnnnnnccccnnnkknccccccccccccccccccccnnnnnccccckkdddddddcccccn',
  'ccccccccnnnncckkdddddcccccnnncccnnncccccnnnnccckkcccccccccccccccnnnnnnwwrrrrrrrrrrrrrrrrrwwnncccccccnnnnnnccccnnnkknccccccccccccccccccccnnnnnccccckkdddddddcccccn',
  'cccccccccccccckkcccccccddddddddcccccccccccccccckkdccccccccccccccccccccwwkkkkkkkkkkkkkkkkkwwccccddddddcccccccccccckkccccccccccccddddddccccccddddddckkcccddddddcccc',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwwrrrrrrrrrrrrrrrrrwwkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwwrrrrrrrrrrrrrrrrrwwkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'ddddddddddddddddddddddddddddwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddddddddddddddd',
  'dddddddddddddddddddddddddddwiiiiissssssssssssssssssssswssssssssssssssssssssssssssssssssssssssssssssssssssswsssssssssssssssssssssssssswddddddddddddddddddddddddddd',
  'ddddddddddddddddddddddddddwffffffigggggggggggggggggggggwgggggggggggggggggggggggggggggggggggggggggggggggggwggggggggggggggggggggggggggggwdddddddddddddddddddddddddd',
  'dddddddddddddddddddddddddwffffffffigggggggggggggggggggggwgggggggggggggggggggggggggggggggggggggggggggggggwggggggggggggggggggggggggggggggwddddddddddddddddddddddddd',
  'ddddddddddddddddddddddddwgffffffffiggggggggggggggggggggggwgggggggggggggggggggggggggggggggggggggggggggggwggggggggggggggggggggggggggggggggwdddddddddddddddddddddddd',
  'dddddddddddddddddddddddwssffffffffisssssssssssssssssssssfswwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwsssssssssssssssssssssssssssssssssswddddddddddddddddddddddd',
  'ddddddddddddddddddddddwsssffffffffisssssssssssssssssssssffsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssswdddddddddddddddddddddd',
  'dddddddddddddddddddddwssssffffffffisssssssssssssssssssssffssssssssssssswwwwwwwwwwwwwwwwwwwsssssssssssfssssssssssssssssssssssssssssssssssssswddddddddddddddddddddd',
  'ddddddddddddddddddddwggggggffffffiggggggggggggggggggggggffggggggggwwwwwgggggggggggggggggggwwwwwggggggffgggggggggggggggggggggggggggggggggggggwdddddddddddddddddddd',
  'dddddddddddddddddddwgggggggffffffigggggggggggggggggggggkkkkgggwwwwgggggggggggggggggggggggggggggwwwwggffggggggggggggggggggggggggggggggggggggggwddddddddddddddddddd',
  'ddddddddddddddddddwgggggggggffffigggggggggggggggggggggggggggwwgggggggggggggggggggggggggggggggggggggwwffgggggggggggggggggggggggggggggggggggggggwdddddddddddddddddd',
  'dddddddddddddddddwggggggggggffffiggggggggggggggggggggggggggwgggggggfggggggggggggggggggggggggggggggggkkkkgggggggggggggggggggggggggggggggggggggggwddddddddddddddddd',
  'ddddddddddddddddwwwwwwwwwwffffffffiwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwffwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwdddddddddddddddd',
  'dddddddddddddddwsssssssffffffffffffffissssssssssssssssssssswsssssssffsssssssssssssssssssssssssssssssswssssssssssssssssssssssssssssssssssssssssssswddddddddddddddd',
  'ddddddddddddddwssssssffffffffffffffffffisssssssssssssssssssswwsssssffsssssssssssssssssssssssssssssswwsssssssssssssssssfssssssssssssssssssssssssssswdddddddddddddd',
  'ddddddddddddddwsssssffffffffffffffffffffissssssssssssssssssssswwwwsffsssssssssssssssssssssssssswwwwsssssssssssssssssssffsssssssssssssssssssssssssswdddddddddddddd',
  'dddddddddddddwgggggffffffffffffffffffffffiggggggggggggggggggggggggkkkkwgggggggggggggggggggwwwwwgggggggggggggggggggggggffgggggggggggggggggggggggggggwddddddddddddd',
  'ddddddddddddwuuuuuuffffffffffffffffffffffiuuuuuuuuuuuuuuuuuuuuuuuuuuuuuwwwwwwwwwwwwwwwwwwwuuuuuuuuuuuuuuuuuuuuuuuuuuuuffuuuuuuuuuuuuuuuuuuuuuuuuuuuuwdddddddddddd',
  'dddddddddddwuuuuuuffffffffffffffffffffffffiuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuffuuuuuuuuuuuuuuuuuuuuuuuuuuuuuwddddddddddd',
  'ddddddddddwuuuuuuuffffffffffffffffffffffffiuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufuuuuuuuuuuuuuuuuuuuuukkkkuuuuuuuuuuuuuuuuuuuuuuuuuuuuuwdddddddddd',
  'dddddddddwuuuuuuuuffffffffffffffffffffffffiuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuffuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuwddddddddd',
  'ddddddddwuuuuuuuuuffffffffffffffffffffffffiuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuffuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuwdddddddd',
  'dddddddwuuuuuuuuuuffffffffffffffffffffffffiuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuffuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuwddddddd',
  'ddddddwuuuuuuuuuuuffffffffffffffffffffffffiuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuffuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuwdddddd',
  'dddddwggggggggggggffffffffffffffffffffffffiggggggggggggggggggggggggggggggggggggggggggggggggggggffggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwddddd',
  'ddddwggggggggggggggffffffffffffffffffffffiggggggggggggggggggggggggggggggggggggggggggggggggggggkkkkggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwdddd',
  'dddwgggggggggggggggffffffffffffffffffffffigggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwddd',
  'ddwggggggggggggggggffffffffffffffffffffffiggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwdd',
  'dwgggggggggggggggggffffffffffffffffffffffigggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggwd',
  'wggggggggggggggggggffffffffffffffffffffffiggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggw',
  'kkkkkkkkkkkkkkkkkkkffffffffffffffffffffffikkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'kkkkkkkkkkkkkkkkkkffffffffffffffffffffffffikkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  'ddddddddddddddddddffffffffffffffffffffffffidddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'ddddddddddddddddddffffffffffffffffffffffffidddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'ddddddddddddddddddffffffffffffffffffffffffidddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'ddddddddddddddddddffffffffffffffffffffffffidddddddddddddddddddddddddtdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'ddddddddddddddddddffffffffffffffffffffffffiddddddddddddddddddddddddtddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'ddddddddddddddddddffffffffffffffffffffffffidddddddddddddddtttttddtdddtddtttttddttttddddtttdddtdddddddddddtdddtdddtttdddtdddtdddtttddddtttdddtttttddttttdddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddtddddddtdddtddddtddddtdddtddtdddtddtdddddddddddttdttddtdddtddttddtddtdddtddtdddtddtddddddtdddtddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddtddddddtdddtddddtddddtdddtddtdddtddtdddddddddddtdtdtddtdddtddtdtdtddtdddtddtddddddtddddddtdddtddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddttttdddtdddtddddtddddttttdddtdddtddtdddddddddddtdtdtddtttttddtdtdtddtttttddtdtttddttttdddttttdddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddtddddddtdddtddddtddddtdddtddtdddtddtdddddddddddtdddtddtdddtddtddttddtdddtddtdddtddtddddddtdtddddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddtddddddtdddtddddtddddtdddtddtdddtddtdddddddddddtdddtddtdddtddtdddtddtdddtddtdddtddtddddddtddtdddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddtdddddddtttdddddtddddttttddddtttdddtttttdddddddtdddtddtdddtddtdddtddtdddtdddtttdddtttttddtdddtddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'dddddddddddddddddffffffffffffffffffffffffffiddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
  'ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
]

export interface CoverRun {
  readonly x: number
  readonly y: number
  readonly w: number
}

export interface CoverInkRuns {
  readonly ink: CoverInk
  readonly runs: readonly CoverRun[]
}

export interface DecodedCover {
  readonly width: number
  readonly height: number
  readonly inks: readonly CoverInkRuns[]
}

/**
 * Groups the scanned runs by ink, in `COVER_INK_KEYS` order.
 *
 * Flat — one level, no parts. The hub figures need a second axis because a prop
 * animates independently of the body; nothing here moves.
 */
export function decodeCover(rows: readonly string[]): DecodedCover {
  const { width, height } = gridSize(rows)
  const byInk = new Map<CoverInk, CoverRun[]>()

  for (const run of scanRuns(rows)) {
    const ink = COVER_INK_BY_CHAR[run.char]
    // Unknown characters are skipped rather than thrown on, the way every other
    // decoder here behaves. A typo loses a pixel; it does not lose the page.
    if (ink === undefined) continue
    const into = byInk.get(ink) ?? []
    into.push({ x: run.x, y: run.y, w: run.w })
    byInk.set(ink, into)
  }

  const inks: CoverInkRuns[] = []
  for (const ink of COVER_INK_KEYS) {
    const runs = byInk.get(ink)
    if (runs !== undefined) inks.push({ ink, runs })
  }
  return { width, height, inks }
}

export const COVER = decodeCover(COVER_GRID)
